# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    # the server name when connecting with adminer on a different network
#    Container hostnames default to their container names ("postgres-db" in my case)
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  #      DEBUG: "true" or
  #      - DEBUG=true
  #    volumes:
  #    - postgres-data:/var/lib/postgresql/data  # Add volume for data persistence


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"  # Change 8081 to the desired external port
    networks:
      - my-network  # Add adminer to the same network as postgres

networks:
  my-network:
    driver: bridge

#volumes:
#  postgres-data:  # Define a volume for PostgreSQL data persistence
